name       : perl-test-mockmodule
version    : 0.172.0
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-v0.172.0.tar.gz : 595b61eee8b70623c312ce33140ef2c2ba9285f9a35128367331bedbe33543b9
homepage   : https://metacpan.org/release/Test-MockModule
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::MockModule - mock subroutines in a module
description: |
    Test::MockModule - mock subroutines in a module
builddeps  :
    - perl-module-build
    - perl-sub-identify
    - perl-super
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-warnings
rundeps    :
    - perl-super
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
