name       : perl-test-mockmodule
version    : 0.173.0
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-v0.173.0.tar.gz : da3c480dc69b5c6dc569506e58ba1cbcbfef3d2e7224ed5189396be5e317db42
homepage   : https://metacpan.org/release/Test-MockModule
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::MockModule - mock subroutines in a module
description: |
    Test::MockModule - mock subroutines in a module
builddeps  :
    - perl-module-build
    - perl-sub-identify
    - perl-super
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-warnings
rundeps    :
    - perl-super
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
