name       : perl-test-mockmodule
version    : 0.177.0
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-v0.177.0.tar.gz : 1bda7a49dcea76076d40a7b6a6c3f3e15e6b19c84b6171df44534d91138f1045
homepage   : https://metacpan.org/release/Test-MockModule
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::MockModule - mock subroutines in a module
description: |
    Test::MockModule lets you temporarily redefine subroutines in other packages for the purposes of unit testing.
builddeps  :
    - perl-module-build
    - perl-sub-identify
    - perl-super
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-warnings
rundeps    :
    - perl-super
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
