name       : perl-test-mockmodule
version    : 0.13
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-0.13.tar.gz : 7473742a0d600eb11766752c79a966570755168105ee4d4e33d90466b7339053
license    : GPL-3.0
component  : programming.perl
summary    : Test::MockModule - mock subroutines in a module
description: |
    Test::MockModule - mock subroutines in a module
builddeps  :
    - perl-module-build
    - perl-sub-identify
    - perl-super
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
