name       : perl-test-mockmodule
version    : '0.15'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-0.15.tar.gz : 1697fedc6c9fedb19351d8e9abb5f9732c192004a21862f84e9cbdedcfb7a35b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::MockModule - mock subroutines in a module
description: |
    Test::MockModule - mock subroutines in a module
builddeps  :
    - perl-module-build
    - perl-sub-identify
    - perl-super
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-warnings
rundeps    :
    - perl-super
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
